services:
  ogmios:
    image: cardanosolutions/cardano-node-ogmios:v6.7.1_9.1.1-${NETWORK:-preview}
    platform: linux/amd64
    command: [
    ]
    volumes:
      # - ./cardano-configurations/network/${NETWORK:-preview}:/config
      - node-ipc-${NETWORK:-preview}:/ipc
      - node-db-${NETWORK:-preview}:/db
    ports:
      - ${OGMIOS_PORT:-1337}:1337

  kupo:
    depends_on:
      - ogmios
    profiles:
      - kupo
    image: cardanosolutions/kupo
    command: [
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json",
      "--host", "0.0.0.0",
      "--port", "${KUPO_PORT:-1442}",
      "--since", "origin",
      "--prune-utxo",
      "--workdir", "/db",
    ]
    volumes:
      - ./cardano-configurations/network/${NETWORK:-preview}:/config
      - node-ipc-${NETWORK:-preview}:/ipc
      - kupo-db-${NETWORK:-preview}:/db
    ports:
      - ${KUPO_PORT:-1442}:1442

volumes:
  # mainnet
  node-db-:
  node-ipc-:
  kupo-db-:
  # preprod
  node-db-preprod:
  node-ipc-preprod:
  kupo-db-preprod:
  # preview
  node-db-preview:
  node-ipc-preview:
  kupo-db-preview:
